// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbfabewnshfjdjfosqxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiZmFiZXduc2hmamRqZm9zcXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODQ1ODgsImV4cCI6MjA3MjY2MDU4OH0.MAmehfB8LDtJdTe4dEHzjLulVlpOhmlbzlSOyjts3sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with api schema - type assertion needed since Database types are for public schema
// The api schema mirrors the public schema structure through views with INSTEAD OF triggers
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'api' as 'public' // Type assertion: api schema mirrors public through views
  }
});
